name: Deploy Backend to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'
          
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci
          
      - name: Test backend
        run: |
          cd backend
          npm test || echo "No tests configured"
          
      - name: Notify Render deployment
        run: |
          echo "Backend changes detected. Render will automatically redeploy."
          echo "Make sure your Render service is connected to this repository."
